madetoraid_lsbbb_controller_default:
    path: /xi/
    defaults: { _controller: madetoraid.lsbbb.controller.main:handle }

madetoraid_lsbbb_controller_install:
    path: /xi/install/
    defaults: { _controller: madetoraid.lsbbb.controller.install:handle }

madetoraid_lsbbb_controller_install_page:
    path: /xi/install/{page}
    defaults: { _controller: madetoraid.lsbbb.controller.install:handle, page: '' }

madetoraid_lsbbb_controller_item:
    path: /xi/item/
    defaults: { _controller: madetoraid.lsbbb.controller.item:handle }

madetoraid_lsbbb_controller_item_id:
    path: /xi/item/{item_id}
    defaults: { _controller: madetoraid.lsbbb.controller.item:handle, item_id: 0 }
    requirements:
      item_id: \d+

madetoraid_lsbbb_controller_ah:
    path: /xi/ah/
    defaults: { _controller: madetoraid.lsbbb.controller.ah:handle }

madetoraid_lsbbb_controller_ah_id:
    path: /xi/ah/{category_id}
    defaults: { _controller: madetoraid.lsbbb.controller.ah:handle, category_id: 0 }
    requirements:
      category_id: \d+

madetoraid_lsbbb_controller_zone:
    path: /xi/zone/
    defaults: { _controller: madetoraid.lsbbb.controller.zone:handle }

madetoraid_lsbbb_controller_zone_id:
    path: /xi/zone/{zone_id}
    defaults: { _controller: madetoraid.lsbbb.controller.zone:handle, zone_id: 0 }
    requirements:
      zone_id: \d+

madetoraid_lsbbb_controller_mob_group:
    path: /xi/zone/{zone_id}/mob/{group_id}
    defaults: { _controller: madetoraid.lsbbb.controller.mob:handle, zone_id: 0, group_id: 0}
    requirements:
      zone_id: \d+
      group_id: \d+

madetoraid_lsbbb_controller_char:
    path: /xi/char/
    defaults: { _controller: madetoraid.lsbbb.controller.char:handle }

madetoraid_lsbbb_controller_char_name:
    path: /xi/char/{char_id}
    defaults: { _controller: madetoraid.lsbbb.controller.char:handle, char_id: 0 }
    requirements:
      char_id: \d+


